### ISSUE TITLE
ログインタイムアウト時(?)にEXEC_BAD_ACCESS

### ISSUE THREAD

**Issue by TETRA2000** [ktsn/float-behind-osx#10]
数回発生。
詳細な再現条件が不明。

**Comment by ktsn** [comment]
これ、didSuccessLogin の時にはすでに dealloc されちゃってたとかなんですかねー。

@TETRA2000 最近発生しますか？

**Comment by TETRA2000** [comment]
見かけないので、一旦閉じますね

**Comment by ktsn** [comment]
:ok_hand:
